### ISSUE TITLE
Feature builders hand-maintain exhaustive DataSource literals, so every port widening breaks them at merge time

### ISSUE THREAD

**Issue by macanderson** [macanderson/oxagen#3423]
Every `apps/app/src/features/*/*.builders.ts` file carries a hand-written, exhaustive object literal of the app's `DataSource` ports. Nothing links those literals to the port shape at compile time except `tsc` over the whole app. So when any PR adds a method to a data source, every builder literal that stubs it becomes structurally invalid — and because the missing port is never exercised, no test in either PR fails. The only thing that catches it is `@oxagen/app#typecheck`, and only after both PRs are in the same tree.

That means the break never appears in the widening PR's own CI. It appears in whichever *other* PR merges next, as a red `checks` run naming a file its author never touched.

## Evidence from a single night (2026-09-19)

`mandate.builders.ts` alone was caught short by **four** different PRs' widenings:

| Widening PR | Port added | Where it went red |
|---|---|---|
| #3352 | `runs.chain` (`get_run_chain`) | #3352, after #3385 merged `mandate.builders.ts` into main |
| #3271 | `spend.priceBook`, `spend.unpricedModels` | #3271, after #3385 merged |
| #3385 | `mandates.get` | #3271, in `features/spend/pricing.test.tsx` |

The #3271 failure is the clearest illustration, because it is symmetric. Two PRs each widened a different source, and each one's fixture mocked the *other's* pre-widening shape:

```
mandate.builders.ts(38,5): error TS2739
  Type '{ byGroup; fleet; drill; waste; budgets; findings; findingEvidence; }'
  is missing the following properties: priceBook, unpricedModels

pricing.test.tsx(98,3): error TS2741
  Property 'get' is missing in type '{ list: Mock<Procedure>; }'
```

Neither PR was wrong in isolation. Both were correct, tested and green on their own branches. They were only invalid together, and only to the typechecker.

Each instance cost a CI cycle. On a branch where `test` runs ~35 minutes and the concurrency group cancels an in-flight run on every push, a cycle is expensive: #3352 had its clock restarted four times in roughly ninety minutes, none of the restarts caused by a defect in its own diff.

## Why it is worth fixing

The defect is not in any of the fixtures. It is that a shared interface surface is mirrored by hand in a dozen places with no mechanical link to the thing it mirrors. Adding a port is a normal, frequent change; it should not be able to break files in unrelated features, and it certainly should not do so only at merge time, in someone else's PR.

The cost scales with parallelism. With one person working the tree it is a minor annoyance caught on the next typecheck. With several sessions working in parallel — which is this repo's stated operating model — it becomes a recurring source of red `checks` runs that each cost a full CI cycle and land on whoever merges next rather than whoever caused them.

Pillars: **maintainability** (the literal cannot drift from the port shape), **efficiency** (removes a recurring class of wasted CI cycles).

## The proposed shape

Give the builders a default-refuse base derived from the port type, and let each feature override only what it actually reads:

```ts
const mandateSource: DataSource = {
  ...refuseAll<DataSource>(),
  mandates: { get: /* the one real read this page does */ },
};
```

`refuseAll<T>()` returns every port of `T` stubbed with the existing `refuse` behaviour — `() => Promise.reject(new Error("not a <Feature> read"))`. Adding a port to `DataSource` then costs nothing in any builder that does not use it, and the "this page does not read that" marker that the current literals encode deliberately is preserved rather than lost.

Two properties the implementation has to keep, because the current literals earn their keep:

- **A test that reaches for an unexpected port must still fail**, not pass on a permissive stub. The default is `refuse`, never `undefined` and never a resolved empty value.
- **The refusal message must still name the feature**, so a test that trips it says which fixture refused and why.

Whether `refuseAll` is derived at runtime from a port manifest or written as a typed constant is an implementation question worth deciding in the PR; the requirement is that adding a port cannot leave a builder silently short.

## SCR-004 case

Larger than the session that found it, and it could not responsibly ride any of the PRs that hit it — each was a feature PR already carrying its own diff, and this touches every feature builder plus a new shared helper with its own test story. Proposed by the agent that fixed the fourth instance.

## Definition of done

- [ ] A `refuseAll<DataSource>()` helper (or equivalent) exists, typed so that adding a port to `DataSource` requires no edit in any builder that does not use it.
- [ ] Its default for every port is a refusal that rejects, so a test reaching an unexpected port fails rather than passing on a stub.
- [ ] The refusal message names the feature whose fixture refused, preserving the diagnostic the current literals give.
- [ ] Every `apps/app/src/features/*/*.builders.ts` is converted to the spread-plus-override form, with no behaviour change to the ports each feature genuinely reads.
- [ ] Inline `DataSource` stubs in feature tests (for example `features/spend/pricing.test.tsx`) either use the helper or are covered by the same guarantee.
- [ ] A test asserts that a builder built from the helper refuses an un-overridden port, and that an overridden port still answers.
- [ ] A test or type-level check demonstrates that adding a new port to `DataSource` does not require editing unrelated builders — the regression guard for this whole class.
- [ ] `apps/app/ARCHITECTURE.md` describes the builder convention, so the next person adding a feature follows it rather than hand-writing a literal.

**Comment by macanderson** [comment]
Triaged P3: kind:debt area:app job:govern pillar:maintainability.
